#!/bin/sh
## Uses the separate jar files for the progs
TOP=/usr/col/scratch1/fuchun/project
MALLET=/usr/col/scratch1/fuchun/mallet
                                                                                                                                                             
JAVA=/exp/rcf/share/X11R5/jdk1.4/bin/java
CP=:$TOP/class:$MALLET/class:$MALLET/lib/mallet-deps.jar
                                                                                                                                                             
DATADIR=$TOP/src/edu/umass/cs/project/extraction/resources

LD_LIBRARY_PATH=$TOP/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH

main=edu.umass.cs.project.extraction.TUI
nice -n 19 $JAVA -Xmx1800m -cp $CP $main --data-file $DATADIR/tagged_references_new.txt \
				 --head-or-ref 1 \
